apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: vets-api
  description: API that provides veterinarian information for the Spring PetClinic project.
  annotations:
    backstage.io/lifecycle: production
  tags:
    - vets
    - petclinic
    - healthcare
spec:
  type: openapi
  lifecycle: production
  owner: team-clinic
  definition: |
    openapi: 3.0.0
    info:
      title: Vets API
      description: API for managing veterinarian data in the Spring PetClinic application.
      version: 1.0.0
    paths:
      /vets:
        get:
          summary: List all veterinarians
          operationId: getVets
          tags:
            - vets
          responses:
            '200':
              description: A list of veterinarians
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Vet'
      /vets/{vetId}:
        get:
          summary: Get a veterinarian by ID
          operationId: getVetById
          parameters:
            - name: vetId
              in: path
              required: true
              description: The ID of the veterinarian to retrieve
              schema:
                type: integer
                format: int64
          responses:
            '200':
              description: Details of a specific veterinarian
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Vet'
            '404':
              description: Vet not found
    components:
      schemas:
        Vet:
          type: object
          properties:
            id:
              type: integer
              format: int64
            firstName:
              type: string
            lastName:
              type: string
            specialties:
              type: array
              items:
                type: string
              description: List of specialties for the veterinarian
